export const CLASSES = [
  {
    classSize: 40,
    id: "Z1H0JlxieeIAsWi6XGLI",
    schedule: "MWF 11:00am - 1:00pm",
    section: "COM231",
    subject: "Information Management",
    subjectCode: "CTINFMGL",
  },
  {
    classSize: 35,
    id: "aBcDeFgHiJkLmNoP",
    schedule: "TTh 9:00am - 11:00am",
    section: "COM101",
    subject: "Introduction to Programming",
    subjectCode: "CS101",
  },
  {
    classSize: 45,
    id: "qRsTuVwXyZ123456",
    schedule: "MWF 2:00pm - 4:00pm",
    section: "COM210",
    subject: "Data Structures and Algorithms",
    subjectCode: "CS210",
  },
  {
    classSize: 30,
    id: "7890aBcDeFgHiJk",
    schedule: "TTh 1:00pm - 3:00pm",
    section: "COM325",
    subject: "Database Systems",
    subjectCode: "CS325",
  },
  {
    classSize: 42,
    id: "lMnOpQrStUvWxYz",
    schedule: "MWF 9:00am - 11:00am",
    section: "COM112",
    subject: "Object-Oriented Programming",
    subjectCode: "CS112",
  },
  {
    classSize: 38,
    id: "1a2b3c4d5e6f7g8h",
    schedule: "TTh 11:00am - 1:00pm",
    section: "COM240",
    subject: "Web Development",
    subjectCode: "CS240",
  },
  {
    classSize: 25,
    id: "i9j0k1l2m3n4o5p",
    schedule: "MWF 1:00pm - 3:00pm",
    section: "COM350",
    subject: "Software Engineering",
    subjectCode: "CS350",
  },
  {
    classSize: 40,
    id: "q6r7s8t9u0v1w2x",
    schedule: "TTh 2:00pm - 4:00pm",
    section: "COM120",
    subject: "Operating Systems",
    subjectCode: "CS120",
  },
  {
    classSize: 32,
    id: "y3z4a5b6c7d8e9f",
    schedule: "MWF 10:00am - 12:00pm",
    section: "COM260",
    subject: "Computer Networks",
    subjectCode: "CS260",
  },
  {
    classSize: 48,
    id: "g0h1i2j3k4l5m6n",
    schedule: "TTh 9:00am - 11:00am",
    section: "COM375",
    subject: "Artificial Intelligence",
    subjectCode: "CS375",
  },
];

export const STUDENTS = [
  {
    name: "Villaver, Jonel",
    studentNumber: "2023-103585",
    email: "villaverj@students.national-u.edu.ph",
    address: "0401 Area C Parola, San Nicolas, Manila",
    course: "BSCS-ML",
  },
  {
    name: "Smith, Alice",
    studentNumber: "2022-987654",
    email: "smitha@students.national-u.edu.ph",
    address: "123 Main Street, Anytown, USA",
    course: "BSCS-DF",
  },
  {
    name: "Johnson, Bob",
    studentNumber: "2023-112233",
    email: "johnsonb@students.national-u.edu.ph",
    address: "456 Oak Avenue, Otherville, USA",
    course: "BSIT-MWA",
  },
  {
    name: "Garcia, Catherine",
    studentNumber: "2021-889900",
    email: "garciac@students.national-u.edu.ph",
    address: "789 Pine Lane, Somewhere City, USA",
    course: "BSIT-MAA",
  },
  {
    name: "Lee, David",
    studentNumber: "2024-224466",
    email: "leed24@students.national-u.edu.ph",
    address: "101 Elm Street, Another Town, USA",
    course: "BSCS-ML",
  },
  {
    name: "Wilson, Emily",
    studentNumber: "2022-775533",
    email: "wilsone@students.national-u.edu.ph",
    address: "222 Cedar Road, Yet Another City, USA",
    course: "BSCS-DF",
  },
  {
    name: "Martinez, Frank",
    studentNumber: "2023-336699",
    email: "martinezf@students.national-u.edu.ph",
    address: "333 Willow Drive, Parola, Manila",
    course: "BSIT-MWA",
  },
  {
    name: "Rodriguez, Grace",
    studentNumber: "2020-664422",
    email: "rodriguezg@students.national-u.edu.ph",
    address: "444 Acacia Court, San Nicolas, Manila",
    course: "BSIT-MAA",
  },
  {
    name: "Chen, Henry",
    studentNumber: "2024-557799",
    email: "chenh@students.national-u.edu.ph",
    address: "555 Mango Street, Intramuros, Manila",
    course: "BSCS-ML",
  },
  {
    name: "Santos, Isabel",
    studentNumber: "2021-448811",
    email: "santosi@students.national-u.edu.ph",
    address: "666 Banana Lane, Binondo, Manila",
    course: "BSCS-DF",
  },
  {
    name: "Reyes, Kevin",
    studentNumber: "2022-123456",
    email: "reyesk@students.national-u.edu.ph",
    address: "777 Grapevine Road, Santa Cruz, Manila",
    course: "BSIT-MWA",
  },
  {
    name: "Cruz, Luna",
    studentNumber: "2023-654321",
    email: "cruzl@students.national-u.edu.ph",
    address: "888 Coconut Grove, Tondo, Manila",
    course: "BSIT-MAA",
  },
  {
    name: "Bautista, Miguel",
    studentNumber: "2024-901234",
    email: "bautistam@students.national-u.edu.ph",
    address: "999 Pineapple Place, Sampaloc, Manila",
    course: "BSCS-ML",
  },
  {
    name: "Domingo, Nina",
    studentNumber: "2020-234567",
    email: "domingon@students.national-u.edu.ph",
    address: "012 Orange Street, Malate, Manila",
    course: "BSCS-DF",
  },
  {
    name: "Pascual, Oscar",
    studentNumber: "2021-567890",
    email: "pascualo@students.national-u.edu.ph",
    address: "345 Lemon Lane, Ermita, Manila",
    course: "BSIT-MWA",
  },
  {
    name: "Evangelista, Patricia",
    studentNumber: "2022-890123",
    email: "evangelistap@students.national-u.edu.ph",
    address: "678 Lime Drive, Paco, Manila",
    course: "BSIT-MAA",
  },
];
